import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/ReactToastify.css";
import HeaderMobile from "@/components/HeaderMobile";
import NavbarContainer from "@/components/containers/NavbarContainer";
import { GeistSans } from "geist/font/sans";
import SidebarContainer from "@/components/containers/SidebarContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt">
      <body className={`${GeistSans.className} overflow-hidden`}>
        <header className="fixed top-0 left-0 right-0 z-10 bg-white shadow">
          <nav>
            <HeaderMobile />
          </nav>
        </header>

        {/* Container com padding-top para evitar que o Sidebar e conteúdo fiquem por trás do header */}
        <div
          className="flex"
          style={{ paddingTop: "0px", height: "100vh" }}
        >
          <SidebarContainer />
          <div className="flex-1 bg-[#F7F8FA] overflow-y-auto">{children}</div>
        </div>

        <ToastContainer
          position="top-right"
          theme="colored"
        />
      </body>
    </html>
  );
}
